//! Verify that the deterministic-nonce pubkey-validity proof (as generated by
//! the WASM lib) is cryptographically valid under the canonical verifier.
//! This proves the browser-generated proof will verify on-chain.

use solana_zk_sdk::{
    encryption::{
        elgamal::{ElGamalKeypair, ElGamalSecretKey},
        pedersen::H,
    },
    transcript::TranscriptProtocol,
    zk_elgamal_proof_program::proof_data::{
        pubkey_validity::PubkeyValidityProofData, ZkProofData,
    },
};
use curve25519_dalek::scalar::Scalar;
use merlin::Transcript;
use sha3::{Digest, Sha3_512};

#[test]
fn deterministic_nonce_proof_verifies() {
    // Fixed secret seed (as the browser would generate).
    let seed = [7u8; 32];
    let secret = ElGamalSecretKey::from_seed(&seed).unwrap();
    let keypair = ElGamalKeypair::new(secret);
    let s = keypair.secret().get_scalar();
    assert!(s != &Scalar::ZERO);
    let s_inv = s.invert();

    // Deterministic nonce: y = hash(seed || domain-sep).
    let mut hasher = Sha3_512::new();
    hasher.update(&seed);
    hasher.update(b"x1-privacy-pubkey-nonce-v1");
    let y = Scalar::from_hash(hasher);
    let Y = (&y * &(*H)).compress();

    // Build the transcript exactly as the canonical proof does.
    let mut transcript = Transcript::new_zk_elgamal_transcript(b"pubkey-validity-instruction");
    transcript.append_message(b"pubkey", &keypair.pubkey().to_bytes());
    transcript.pubkey_proof_domain_separator();
    transcript.append_point(b"Y", &Y);
    let c = transcript.challenge_scalar(b"c");
    let z = &(&c * &s_inv) + &y;

    // Assemble the 96-byte PubkeyValidityProofData (Pod, repr C).
    let mut data = [0u8; 96];
    data[..32].copy_from_slice(&<[u8; 32]>::from(keypair.pubkey()));
    data[32..64].copy_from_slice(Y.as_bytes());
    data[64..96].copy_from_slice(z.as_bytes());
    let proof: &PubkeyValidityProofData = bytemuck::from_bytes(&data);

    // Verify with the canonical verifier.
    proof.verify_proof().expect("deterministic-nonce proof must verify");
}
